from time import sleep

from PyQt6.QtWidgets import QFileDialog, QMainWindow, QApplication, QLabel, QFrame
from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtCore import QTimer, QEventLoop

# Form implementation generated from reading ui file 'disp.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1044, 618)
        MainWindow.setMinimumSize(QtCore.QSize(1044, 618))
        MainWindow.setMaximumSize(QtCore.QSize(1044, 618))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 173, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 173, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 173, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 173, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(620, 100, 391, 31))
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 961, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(560, 90, 51, 51))
        self.submit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Desktop/5290109.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.submit.setIcon(icon)
        self.submit.setIconSize(QtCore.QSize(50, 50))
        self.submit.setObjectName("submit")
        self.content = QtWidgets.QListWidget(parent=self.centralwidget)
        self.content.setGeometry(QtCore.QRect(20, 180, 1011, 321))
        self.content.setObjectName("content")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(70, 510, 971, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 1011, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.boxes = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.boxes.setContentsMargins(0, 0, 0, 0)
        self.boxes.setObjectName("boxes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ГРАФИЧЕСКАЯ РЕАЛИЗАЦИЯ АЛГОРИТМОВ"))






class Menu(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("Главное меню")
        self.comboBox.addItem('Бинарный поиск')
        self.initUI()
        self.num = 13

    def initUI(self):
        self.submit.clicked.connect(self.real)


    def real(self):
        if self.comboBox.currentText() == 'Бинарный поиск':
            self.bin_a()


    def action(self):
        myWidget = self.boxes.itemAt(self.num // 2).widget()
        print(self.call)
        if myWidget.text() == '9':
            myWidget.setStyleSheet("""
                   QLabel {
                      background-color: green;
                      color: black;
                      border: 2px solid #2980b9;
                      border-radius: 3px;
                      padding: 10px;
                      font-weight: bold;
                   }
                    """)
            self.boxes.update()
            return

        if self.call % 2 == 0:
           myWidget = self.boxes.itemAt(self.num // 2).widget()
           myWidget.setStyleSheet("""
               QLabel {
                  background-color: grey;
                  color: black;
                  border: 2px solid #2980b9;
                  border-radius: 3px;
                  padding: 10px;
                  font-weight: bold;
               }
                """)
           self.boxes.update()
        elif self.call % 2 == 1:
            if int(self.boxes.itemAt(self.num // 2).widget().text()) > 9:
                #print(int(self.boxes.itemAt(self.num // 2).widget().text()))
                for i in range(self.num // 2 + 1, 13):
                    myWidget = self.boxes.itemAt(i).widget()
                    myWidget.setStyleSheet("""
                        QLabel {
                           background-color: grey;
                           color: black;
                           border: 2px solid #2980b9;
                           border-radius: 3px;
                           padding: 10px;
                           font-weight: bold;
                        }
                         """)
                self.right = self.num // 2
                self.num = (self.left + self.num // 2)
                self.boxes.update()
            else:
                #print(int(self.boxes.itemAt(self.num // 2).widget().text()))
                for i in range(self.num // 2):
                    myWidget = self.boxes.itemAt(i).widget()
                    myWidget.setStyleSheet("""
                        QLabel {
                           background-color: grey;
                           color: black;
                           border: 2px solid #2980b9;
                           border-radius: 3px;
                           padding: 10px;
                           font-weight: bold;
                        }
                         """)
                self.right = self.num // 2
                self.num = (13 + self.num // 2)
                self.boxes.update()




    def bin_a(self):
        self.statusbar.showMessage("В работе", 20000)
        self.left = 0
        self.right = 13
        self.num = 13
        while self.boxes.count() > 0:
            item = self.boxes.takeAt(0)

        n = [i for i in range(1, 14)]
        for j in n:
            lab = QLabel(f'{j}')
            lab.setFixedSize(50, 50)
            lab.setStyleSheet("""
    QLabel {
        background-color: #3498db;
        color: black;
        border: 2px solid #2980b9;
        border-radius: 3px;
        padding: 10px;
        font-weight: bold;
    }
""")

            self.boxes.addWidget(lab)
        self.centralwidget.setLayout(self.boxes)
        self.setCentralWidget(self.centralwidget)
        for k in range(6):
            self.call = k
            QTimer.singleShot(3000, self.action)






if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Menu()
    ex.show()
    sys.exit(app.exec())
